### ISSUE TITLE
AndroidIDE exception when using dyadic slash operator

### ISSUE THREAD

**Issue by eisterman** [dzaima/APL#2]
When the / operator is used in dyadic syntax (compress operator), the AndroidApp throw an exception.

Note that I'm reporting only the first line of the error because the absence of the possibility to copy the output of the app:
`java.lang.ClassCastException: APL.types.arrs.BitArr cannot be cast to APL.types.fun`

I think the problem is linked with the monadic form of /, where is needed a function. 

To reproduce the error I've used `0 1 0 1 1 0 1 / 1 2 3 4 5 6 7` to be sure the problem is truly /.

**Comment by dzaima** [comment]
[`/` is only reduce](https://github.com/dzaima/APL/blob/7b80ca524cb57c66086b4ea656521a0c074c3473/docs/differences.txt#L1) in dzaima/APL. Replicate is available as `⌿`.

I should make the error more descriptive though. There are many similar cases - `1⍣1⊢1`, `1⍡1⊢1`, `1ᑈ⍨1`, `1ᐵ⍨1`, `1⍁⍪1`, `1⍥1⍨1`, `1⍤1⍨1`, `1⍫1⊢1`, `1⍢1⊢1`, probably some more I've missed - I just haven't yet bothered to check for these cases yet.

No easy way to allow copying from the log is another problem of me writing custom GUI code rather than anything native. At some point i'll see what i can do.
